apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
  namespace: auth
data:
  config.yaml: |
    issuer: https://three-tier.local/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556

    staticClients:
    - id: kubernetes-cluster
      redirectURIs:
      - 'http://localhost:8000/callback'
      name: 'Kubectl Login Client'
      secret: super-secret-cluster-handshake-string

    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Ov23ctkp3QmLNh4MmMQb
        clientSecret: f3b6f92d105a402238653755e9bf4f2e955d668e
        redirectURI: https://three-tier.local/dex/callback
        orgs:
        - name: k8s-project01
          teams:
          - developers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex-serviceaccount
      containers:
      - name: dex
        image: ghcr.io/dexidp/dex:v2.41.0
        command: ["dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: http
          containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
      volumes:
      - name: config
        configMap:
          name: dex-config
---
apiVersion: v1
kind: Service
metadata:
  name: dex-service
  namespace: auth
spec:
  selector:
    app: dex
  ports:
  - protocol: TCP
    port: 5556
    targetPort: 5556
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex-ingress
  namespace: auth
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - three-tier.local
    secretName: dex-tls-secret
  rules:
  - host: three-tier.local
    http:
      paths:
      - path: /dex
        pathType: Prefix
        backend:
          service:
            name: dex-service
            port:
              number: 5556
